; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.port = COMx  ; 替换为ESP32-S3实际串口（如COM3）
monitor_speed = 115200
monitor_port = COMx      ; 与上传端口一致
lib_deps = adafruit/DHT sensor library@^1.4.4  ; 引入DHT传感器库